### PR TITLE
Fix off64_t type on FreeBSD systems

### PR DESCRIPTION
**Pull request by andersensam**
The off64_t type is not used on FreeBSD systems. Changing to off_t fixes compilation.

### CODE REVIEW

**Comment by Tatsh** [comment]
This was already addressed for macOS and should be done the same way. https://github.com/vitalif/grive2/blob/master/CMakeLists.txt#L14

**Comment by andersensam** [comment]
Hi Tatsh, I've gone ahead and rewritten the change to simulate what's been done on macOS. There isn't an "APPLE" variable for FreeBSD specifically [(see here)](https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/How-To-Write-Platform-Checks) hence the slightly different formatting.

**Comment by Tatsh** [comment]
A better test is to write a real compilation test here to see if a simple block of code using `off64_t` works, and if it does not, try `off_t`. But that's for the future. I am worried this project is no longer receiving any attention from the owner.

**Comment by Tatsh** [comment]
Also, this can be simplified to be part of the APPLE check.

```cmake
if ( APPLE OR CMAKE_SYSTEM_NAME MATCHES "FreeBSD" )
```

Someone else #115 on OpenBSD has a similar need so you may want to add `CMAKE_SYSTEM_NAME MATCHES "OpenBSD"` as well.

[if](https://cmake.org/cmake/help/latest/command/if.html?highlight=#command:if)
[CMAKE_SYSTEM_NAME](https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_NAME.html#variable:CMAKE_SYSTEM_NAME)
[Expected `uname -s` output from CMake source](https://github.com/Kitware/CMake/blob/master/Modules/CMakeDetermineSystem.cmake#L10)

**Comment by vitalif** [comment]
Your branch has more changes than just off64_t, but I just merged something off64_t-related. So please check if it builds under FreeBSD now :)

**Pull request closed without merging**
