### PR TITLE
Add instruction for replacing the OAuth2 client

### PR DESCRIPTION
**Pull request by AmonRaNet**
This is cherry-pick from pull request https://github.com/vitalif/grive2/pull/242
Additionally added a step about removing of the old configuration file.

### CODE REVIEW

**Comment by AmonRaNet** [comment]
Hope this is good for @jankatins. But too many people ask the same questions, and here is more or less complete instruction.

**Comment by zjsr** [comment]
This instruction for replacing the OAuth2 client, particularly the need to remove the old configuration file, was very helpful.  Grive now working for me! Thank you.

**Comment by AmonRaNet** [comment]
@vitalif Can we merge?

**Comment by vitalif** [comment]
Yes, thanks, however I'd also notice current "approval" issues

**Comment by vitalif** [comment]
OK, I've added a note

**Pull request merged**
