### PR TITLE
Add systemd unit to enable both timer and changes based syncs

### PR DESCRIPTION
**Pull request by jankatins**
Now it's enough to enable and start `grive@<folder>.service`.

### CODE REVIEW

**Comment by jankatins** [comment]
Updated against current master (README.md had a conflict)

**Comment by jankatins** [comment]
@vitalif Any chance to get this merged and released? I soon have to setup a fedora laptop and it would be super nice to have this in there :-)

**Comment by jankatins** [comment]
@vitalif ping again, just saw that you were active again. I'm basically running this via my own fork since about half a year...

**Comment by vitalif** [comment]
> @vitalif ping again, just saw that you were active again. I'm basically running this via my own fork since about half a year...

Yeah, of course

**Pull request merged**
