### PR TITLE
Stop throwing an error when rate limit is exceeded

### LINKED ISSUE #145: Error: Rate Limit Exceeded
I encounter the following exception when I try to sync using the `grive` command

    exception: /build/grive2-2Hxkkx/grive2-0.5.1/libgrive/src/protocol/AuthAgent.cc(159): Throw in function long int gr::AuthAgent::CheckHttpResponse(long int, const string&, const gr::http::Header&)
    Dynamic exception type: boost::exception_detail::clone_impl<gr::http::Error>
    [gr::expt::BacktraceTag*] = #0 0x578d79 grive gr::Exception::Exception()
    #1 0x5597d7 grive gr::http::Error::Error()
    #2 0x56119c grive gr::AuthAgent::CheckHttpResponse(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, gr::http::Header const&)
    #3 0x560c02 grive gr::AuthAgent::Request(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, gr::SeekStream*, gr::DataStream*, gr::http::Header const&, unsigned long long)
    #4 0x560560 grive gr::http::Agent::Get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, gr::DataStream*, gr::http::Header const&, unsigned long long)
    #5 0x556dd8 grive gr::v2::Feed2::GetNext(gr::http::Agent*)
    #6 0x5442a9 grive gr::Drive::DetectChanges()
    #7 0x50b9da grive Main(int, char**)
    #8 0x50c1e9 grive main
    #9 0x7fcead0c3830 /lib/x86_64-linux-gnu/libc.so.6 __libc_start_main
    #10 0x50a4b9 grive _start

    [gr::http::ResponseBodyTag*] = {
     "error": {
      "errors": [
       {
        "domain": "usageLimits",
        "reason": "rateLimitExceeded",
        "message": "Rate Limit Exceeded"
       }
      ],
      "code": 403,
      "message": "Rate Limit Exceeded"
     }
    }

### PR DESCRIPTION
**Pull request by patrickkettner**
fixes #145

### CODE REVIEW

**Comment by vitalif** [comment]
Hi, is 403 only caused by rate limiting?

**Comment by patrickkettner** [comment]
Only 403 reference in the docs is for rate limiting

**Comment by pyron83** [comment]
I confirm that this mod fixes the 403 "rate-limit exceeded" problem on my environment

thanks

**Comment by ollipa** [comment]
> Only 403 reference in the docs is for rate limiting

According to the latest API documentation, 403 errors are not caused only by rate limiting:

https://developers.google.com/drive/v3/web/handle-errors
> 403: Daily Limit Exceeded
403: User Rate Limit Exceeded
403: Rate Limit Exceeded
403: Sharing Rate Limit Exceeded
403: The user has not granted the app {appId} {verb} access to the file {fileId}
403: The user does not have sufficient permissions for file {fileId}
403: App with id {appId} cannot be used within the authenticated user's domain

**Comment by vitalif** [comment]
> According to the latest API documentation, 403 errors are not caused only by rate limiting:

+1, add a check for rate limiting error message and I'll merge it:)

**Comment by patrickkettner** [comment]
Got a link?

**Comment by vitalif** [comment]
https://developers.google.com/drive/api/v3/handle-errors but never mind, I've just committed a variation of your patch with "exponential backoff"

**Pull request closed without merging**
