### PR TITLE
Syncer.hh: fix build with gcc-12

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by MonterosMN** [comment]
This fixed my compilation issues

**Comment by jasper1378** [comment]
This also fixed my compilation issue.

**Comment by dee42** [comment]
@vitalif Please merge this

**Comment by jumoog** [comment]
bump

**Review by jumoog — APPROVED** [review]

**Comment by vitalif** [comment]
Thanks :)

**Pull request merged**
